---

- name: restart sshd
  service:
    name: ssh
    state: restarted

- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: reload systemctl
  command: systemctl daemon-reload

- name: mount all
  command: "{{ item }}"
  with_items: 
    - "umount -a"
    - "mount -a"

- name: reboot
  reboot:

- name: timesyncd
  command: "{{ item }}"
  with_items: 
    - "timedatectl show-timesync --all"
    - "timedatectl status"
    - "systemctl restart systemd-timesyncd"
    - "timedatectl set-ntp true"
    - "timedatectl status"

- name: Start docker on boot
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Restart Docker
  systemd:
    name: docker
    state: restarted