---
# vars file for service

_service_required_packages:
  default: []
  Amazon-2:
    - procps-ng
  Amazon-2018:
    - procps
  Debian:
    - psmisc
  RedHat:
    - psmisc
  Suse:
    - psmisc

service_required_packages: "{{ _service_required_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_service_required_packages[ansible_os_family] | default(_service_required_packages['default'] )) }}"
