---
- name: Create client and join {{groups.server.0}} with consul {{version}}
  command:
  args:
    argv:
      - hashi-up
      - consul
      - install
      - --ssh-target-addr
      - "{{hostvars[item].ansible_host}}"
      - --ssh-target-key
      - "{{ssh_key}}"
      - --ssh-target-user
      - "{{nomad_username}}"
      - --version
      - "{{version}}"
      # - --encrypt
      # - "{{gossip_key}}"
      - --retry-join 
      - "{{hostvars[groups.server.0].ansible_host}}"
  with_items: "{{ groups['client'] }}"
  when: master_created is succeeded and http_api_result is succeeded
  register: client_joined
  notify: reboot

- name: Debug report of client joined
  debug: var=client_joined
  when: client_joined is failed or debug_nodes
