---

- name: "Set variables"
  set_fact:
    is_server: False

- name: Generate consul.hcl config file
  template:
    src: consul.hcl.j2
    dest: /tmp/consul-{{ item }}.hcl
  with_items: "{{ groups['client'] }}"

- name: Create client and join with consul {{version}}
  command:
  args:
    argv:
      - hashi-up
      - consul
      - install
      - --ssh-target-addr
      - "{{ hostvars[item].ansible_host }}"
      - --ssh-target-key
      - "{{ ssh_key }}"
      - --ssh-target-user
      - "{{ hashi_user }}"
      - --version
      - "{{ version }}"
      - --config-file
      - /tmp/consul-{{ item }}.hcl
  with_items: "{{ groups['client'] }}"
  when: master_created is succeeded and http_api_result is succeeded
  register: client_joined

- name: Debug report of client joined
  debug: var=client_joined
  when: client_joined is failed or debug_nodes
