---

- name: "Set variables"
  set_fact:
    is_server: False

- name: Generate consul.hcl config file
  template:
    src: consul.hcl.j2
    dest: /tmp/consul-{{ item }}.hcl
  with_items: "{{ groups['client'] }}"

- name: Create client and join with consul {{version}}
  command:
  args:
    argv:
      - hashi-up
      - consul
      - install
      - --ssh-target-addr
      - "{{ hostvars[item].ansible_host }}"
      - --ssh-target-key
      - "{{ ssh_key }}"
      - --ssh-target-user
      - "{{ hashi_user }}"
      - --version
      - "{{ version }}"
      - --config-file
      - /tmp/consul-{{ item }}.hcl
  with_items: "{{ groups['client'] }}"
  when: master_created is succeeded and http_api_result is succeeded
  register: client_joined

- name: Check API availability of client
  uri:
    url: "http://{{ hostvars[item].ansible_facts.tailscale0.ipv4.address }}:8500/v1/catalog/datacenters"
    method: GET
    validate_certs: False
    status_code: 200
    body_format: json
  with_items: "{{ groups['client'] }}"
  register: http_api_result
  retries: 6
  delay: 15
  until: http_api_result is not failed
  when: client_joined is succeeded

- name: Debug report of client joined
  debug: var=client_joined
  when: client_joined is failed or debug_nodes
