---
- import_tasks: install.yml

- import_tasks: config-antigen.yml

- name: console setup for Debian family distributions
  include_tasks: debian-console-setup.yml
  when: ansible_os_family == 'Debian'


