---

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  become: yes
  apt:
      name: "{{ packages }}"
  vars:
      packages:
        - gnupg

- name: Tailscale Signing Key
  apt_key:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.gpg
    state: present

- name: Add Tailscale Deb
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main
    state: present

- name: Install Tailscale
  apt:
    name: tailscale
    state: latest
    update_cache: yes
  notify: enable tailscaled service

- name: Check if Tailscale is connected
  command: tailscale status
  register: tailscale_status
  ignore_errors: true

- name: Bring Tailscale Up
  become: yes
  command: tailscale up --authkey={{ tailscale_auth_key }}
  register: tailscale_start
  when: '"100."  not in tailscale_status.stdout'
  notify: Confirm Tailscale is Connected
